version: '3.8'
services:
  mysql_orders:
    image: mysql:8.0
    container_name: delivone_orders_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: projeto5_orders
    ports:
      - '3303:3306'
    volumes:
      - db_orders_data:/var/lib/mysql
volumes:
  db_orders_data: